vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        book:
            uri_prefix: /images/books
            upload_destination: '%kernel.project_dir%/public/images/books'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        products:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
